version: '3.8'

services:
    rpi4:
        container_name: rpi4
        image: "${USER}/rpi4"
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"    ## docker run --user=$USER
        stdin_open: true         ## docker run -i
        tty: true                ## docker run -t
        #privileged: true
        environment:
          - USER
        env_file:
          - .env
        volumes:
          ## folders not need to be around
          - ~/.gitconfig:/home/$USER/.gitconfig
          - ~/.ssh:/home/$USER/.ssh
          - ~/.buildroot:/home/$USER/buildroot
          ## folder must be around
          - type: bind
            source: ./build_configs
            target: /home/$USER/configs
